version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Password123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  webapi:
    build:
      context: .
      dockerfile: Mariusz.Piotrowski/Dockerfile
    container_name: webapi
    depends_on:
      - sqlserver
    ports:
      - "5181:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=sqlserver;Database=MariuszDb;User Id=sa;Password=YourStrong!Password123;

volumes:
  sql_data:
